//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tweeple.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IValidateUser")]
    public interface IValidateUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidateUser/validate", ReplyAction="http://tempuri.org/IValidateUser/validateResponse")]
        bool validate(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IValidateUserChannel : Tweeple.ServiceReference1.IValidateUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidateUserClient : System.ServiceModel.ClientBase<Tweeple.ServiceReference1.IValidateUser>, Tweeple.ServiceReference1.IValidateUser {
        
        public ValidateUserClient() {
        }
        
        public ValidateUserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidateUserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateUserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateUserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool validate(string username, string password) {
            return base.Channel.validate(username, password);
        }
    }
}
